### ISSUE TITLE
Questions about performance results

### ISSUE THREAD

**Issue by LightersWang** [WitchPuff/CRC-Diagnose#1]
Hi!

Thanks for your great work in this repo. 

I'm curious about the accuracy of your provided ResNet and ViT on the NCT-CRC-HE-100K dataset after training with your codebase.

**Comment by WitchPuff** [comment]
Hi :D
Sure, here's the performance after 40 epochs:
ResNet: 1 for trainset, 0.93 for testset
ViT: 0.929 for trainset, 0.886 for testset

Hope it helps!

**Comment by LightersWang** [comment]
Thanks for your help!
